// ======================================
// /driver/districts - Kezang Gelley
// ======================================
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import DistrictListCard from "../../components/driver/districtListCard";
import { api } from "../../utils/api";

const Home: NextPage = () => {
  // Get the districts from the API
  // TODO: Replace this with an API call
  
  const getDistrictData = api.driver.getDistricts.useQuery(); 
  const districts = getDistrictData.data?.districts;

  // const districts = [
  //   {
  //     id: 1,
  //     name: "Thimphu",
  //     // image: "/images/districts/thimphu.jpg",
  //   },
  //   {
  //     id: 2,
  //     name: "Paro",
  //     // image: "/images/districts/paro.jpg",
  //   },
  //   {
  //     id: 3,
  //     name: "Chukha",
  //   },
  // ];
  
  if(!districts) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>Districts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-10 flex min-h-screen flex-col items-center bg-gradient-to-b from-[#ffffff] to-[#ffffff]">
        {/* Back Arrow and Select District Section */}
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          className="absolute left-10 top-10 mt-4 h-6 w-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M15.75 19.5L8.25 12l7.5-7.5"
          />
        </svg>
        <h1 className="text-extrabold mt-3 block text-xl font-medium text-black">
          Select District
        </h1>

        <h2 className="block text-xl font-bold  text-gray-700">District</h2>

        <div className="mx-auto flex rounded-full w-3/4 flex-col gap-10 shadow-sm">
          {/* Search District Search Field */}
          <div className="relative w-full">
            <input
              className="h-10 w-full rounded-full border bg-white pl-4 pr-10 text-sm shadow-xl"
              id="search"
              type="search"
              placeholder="Search District..."
            />

            <button
              type="button"
              className="absolute top-1/2 right-1 -translate-y-1/2 rounded-full bg-gray-50 p-2 text-gray-600 transition hover:text-gray-700"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
            </button>
          </div>
        </div>

        {/* District Listings */}
        <div className="mt-12 flex flex-col gap-6">
          {
          districts.map((district) => (
            <DistrictListCard district={district}/>
          ))
          }
        </div>
        
        {/* NOTE: The User will select the zone and need not press NEXT button
          This button might need it in the RMA API scenario*/}
        
        {/* <Link
          href="/driver/district/zone"
          className="mt-10 flex w-3/4 items-center justify-center "
        >
          <button
            type="button"
            className="ml-0 mb-2 inline w-full rounded-full bg-blue-600 px-6 py-2 text-white hover:bg-white hover:text-blue-600 hover:outline-double"
          >
            Next
          </button>
        </Link> */}
      </main>
    </>
  );
};

export default Home;
