// ======================================
// /driver/offenseStatus - Nima Yoezer
// ======================================
import Head from "next/head";
import Link from "next/link";

export default function OffenseStatus() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Fine Status Card */}
        <div className="flex h-screen items-center justify-center">
          <div>
            <div className="flex justify-center">
              <div className="block max-w-sm rounded-lg bg-white p-6 shadow-lg">
                <h5 className="mb-2 text-xl font-medium leading-tight text-gray-900">
                  You've Previous Fines to Pay
                </h5>
                {/* TODO: Redesign and align using Grid */}
                <p className="mb-4 text-base text-gray-700">
                  Parking Fee: Nu. 20 <br />
                  Total Offense: 3 Times <br />
                  Fine Amount: Nu. 300 <br />
                  Total Amount: Nu. 320 <br />
                </p>
                {/* Make the button center aligned */}
                <div className="flex items-center justify-center">
                  <Link href={"/driver/offenseDetails"}>
                    <button
                      type="button"
                      className=" mt-5 inline-block rounded bg-blue-600 px-6 py-2.5 text-xs font-medium uppercase leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg"
                    >
                      Details
                    </button>
                  </Link>
                </div>
              </div>
            </div>

            {/* Continue Button */}
            <Link href={"/driver/rma"}>
              <div className="mt-10 flex justify-center space-x-2">
                <button
                  type="button"
                  className="inline-block rounded bg-blue-600 px-6 py-2.5 text-xs font-medium uppercase leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg"
                >
                  Continue
                </button>
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
