// ===================================
// /driver/offenseDetails - Dechen Pelden
// ===================================
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { MdOutlineHistoryToggleOff } from "react-icons/md";
import OffenseDetailCard from "../../components/driver/offenseDetailCard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Past Report</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="ma-w-3xl flex-col space-y-4 p-6 dark:bg-gray-900 dark:text-gray-100 sm:p-10">
          <div>
            <div className="fixed top-6 left-5 right-0">
              <a
                href="#"
                className="inline-flex h-8 w-8 items-center justify-center rounded border border-gray-100"
              >
                <span className="sr-only">Prev Page</span>
                <Link href={"/driver/offenseStatus"}>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </Link>
              </a>
            </div>

            <div>
              <h2 className="flex flex-col items-center justify-center text-xl font-semibold md:text-4xl">
                Details
              </h2>
            </div>

            <div>
              <Link
                href="/driver/parkingHistory"
                className="left-45 fixed top-7 right-5"
              >
                <MdOutlineHistoryToggleOff className="h-6 w-6 text-gray-500" />
              </Link>
            </div>
          </div>
        <div className="flex flex-col gap-5">
          <OffenseDetailCard />
          <OffenseDetailCard />
          <OffenseDetailCard />
        </div>
        </div>
      </main>
    </>
  );
};

export default Home;
