// ======================================
// /driver/parkingHistory - Dechen Pelden
// ======================================


import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Booking History</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <div className="flex-col ma-w-3xl p-6 space-y-4 sm:p-10 dark:bg-gray-900 dark:text-gray-100">
       
      <div className="fixed top-6 left-2 right-0">
        <a href="#" className="flex flex-col h-8 w-8 items-center justify-center rounded border border-black-600">
      <span className="sr-only">Prev Page</span>
      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd"
          d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
          clip-rule="evenodd"/>
      </svg>
    </a>
        <div className="fixed top-6 left-2 right-0">
        <h2 className="flex flex-col justify-center items-center text-xl font-semibold"  >Booking History</h2>
        </div>
      </div>


        <ul className="flex flex-col divide-y divide-gray-700">
          <li className="flex flex-col py-10 sm:flex-row sm:justify-between">
            
              <div className="flex flex-col justify-between pb-4 shadow-xl shadow-blue-300">
                <div className="flex-row justify-between  pb-2 space-x-2 p-2 ">
                  <div className="space-y-1 space-x-2">
                    <h3 className="text-lg font-semibold leading-snug sm:pr-8">Zangdhopelri, Phuntsholing</h3>
                    <p className="text-sm dark:text-gray-400">12/12/2022, 2:40 pm</p>
                    <p className="text-sm dark:text-gray-400">Duration: 1hr</p>
                    <p className="text-sm dark:text-gray-400">Booking Fee: Nu.50</p>
                    <span className="text-sm text-red-600 ">Fine cost: Nu.0</span>
                  </div>
                </div>
              </div>

              <div className="flex flex-col justify-between pb-4 shadow-xl shadow-blue-300">
                <div className="flex-row justify-between  pb-2 space-x-2 p-2 ">
                  <div className="space-y-1 space-x-2">
                    <h3 className="text-lg font-semibold leading-snug sm:pr-8">Desup Line, Phuntsholing</h3>
                    <p className="text-sm dark:text-gray-400">12/12/2022, 8:00 am</p>
                    <p className="text-sm dark:text-gray-400">Duration: 30mins</p>
                    <p className="text-sm dark:text-gray-400">Booking Fee: Nu.25</p>
                    <span className="text-sm text-red-600 ">Fine cost: Nu.10</span>
                  </div>
                </div>
              </div>

              <div className="flex flex-col justify-between pb-4 shadow-xl shadow-blue-300">
                <div className="flex-row justify-between  pb-2 space-x-2 p-2 ">
                  <div className="space-y-1 space-x-2">
                    <h3 className="text-lg font-semibold leading-snug sm:pr-8">Tashi Complex, Phuntsholing</h3>
                    <p className="text-sm dark:text-gray-400">12/12/2022, 9:40 am</p>
                    <p className="text-sm dark:text-gray-400">Duration: 30mins</p>
                    <p className="text-sm dark:text-gray-400">Booking Fee: Nu.50</p>
                    <span className="text-sm text-red-600 ">Fine cost: Nu.30</span>
                  </div>
                </div>
              </div>

              <div className="flex flex-col justify-between pb-4 shadow-xl shadow-blue-300">
                <div className="flex-row justify-between  pb-2 space-x-2 p-2 ">
                  <div className="space-y-1 space-x-2">
                    <h3 className="text-lg font-semibold leading-snug sm:pr-8">Zangdhopelri, Phuntsholing</h3>
                    <p className="text-sm dark:text-gray-400">12/12/2022, 2:40 pm</p>
                    <p className="text-sm dark:text-gray-400">Duration: 30mins</p>
                    <p className="text-sm dark:text-gray-400">Booking Fee: Nu.50</p>
                    <span className="text-sm text-red-600 ">Fine cost: Nu.30</span>
                  </div>
                </div>
              </div>

        
          </li>
        </ul>
      </div>
      </main>
    </>
  );
};

export default Home;
