// ======================================
// /driver/parkingHistory - Dechen Pelden
// ======================================

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ParkingHistoryCard from "../../components/driver/parkingHistoryCard";

// react icon
import { BiArrowBack } from "react-icons/bi";

const ParkingHistory: NextPage = () => {
  return (
    <>
      <Head>
        <title>Parking History</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-3/4 m-auto flex-col space-y-4 p-6 dark:bg-gray-900 dark:text-gray-100 sm:p-10">
          <div className="top-6 left-2 right-0 flex flex-row gap-10">
            <Link href={"/driver/checkSession"}>
              <button>
                <BiArrowBack className="h-8 w-8" />
              </button>
            </Link>

            <h1 className=" text-2xl font-semibold md:text-4xl">
              Parking History
            </h1>
          </div>

          <div className="flex flex-col gap-10">
            <ParkingHistoryCard />
            <ParkingHistoryCard />
            <ParkingHistoryCard />
            <ParkingHistoryCard />
          </div>

          {/* <div className="flex flex-col justify-between pb-4 shadow-xl shadow-blue-300">
                <div className="flex-row justify-between  space-x-2 p-2 pb-2 ">
                  <div className="space-y-1 space-x-2">
                    <h3 className="text-lg font-semibold leading-snug sm:pr-8">
                      Desup Line, Phuntsholing
                    </h3>
                    <p className="text-sm dark:text-gray-400">
                      12/12/2022, 8:00 am
                    </p>
                    <p className="text-sm dark:text-gray-400">
                      Duration: 30mins
                    </p>
                    <p className="text-sm dark:text-gray-400">
                      Booking Fee: Nu.25
                    </p>
                    <span className="text-sm text-red-600 ">
                      Fine cost: Nu.10
                    </span>
                  </div>
                </div>
              </div> */}
        </div>
      </main>
    </>
  );
};

export default ParkingHistory;
