// ===================================
// /driver/paymentConfirmation - Sonam Deki
// ===================================
import Head from 'next/head'

export default function PaymentConfirmation () {
    return (
        <>
        <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
      <div className="w-full xl:w-1/2 p-8  flex flex-col justify-center items-center">
      <div id = "confirmation box" className="rounded-lg bg-blue-600 h-50  w-2/4 mt-20 " >
        <label>Your Payment has been successful!</label><br></br>
        <input type="checkbox" id="payment" name="paymentConfirmation" value="#" className="rounded-full"></input>

      </div>
       

       <div id="button">
        <label>Click here to know your parking status</label><br></br>
       <button type="button" className="rounded-3xl bg-blue-400  text-white shadow-xl backdrop-blur-md transition-colors duration-300 hover:bg-blue-600 bg-opacity-50 px-10 py-2">Parking Session</button>
       
       </div>
       </div>

      </main>
        </>
    )
}